### ISSUE TITLE
Woocommerce rechtssicher 

### ISSUE THREAD

**Issue by netzlum** [rpi-virtuell/ci-site#13]
Woocommerce ist wohl in der Basisinstallation nicht für eine rechtssichere Ausstattung für den deutschen Markt ausgelegt. Es gibt aktuell wohl zwei Erweiterungen, die gepflegt werden: Woocommerce German Market oder WooCommerce Germanized (letzteres in der Basisausstattung kostenlos) Wie sollen wir hierbei verfahren? Meine Wordpress-Kollegen im Büro haben schon mit beiden gearbeitet.

**Comment by johappel** [comment]
Germanized ist installiert
