### ISSUE TITLE
Im RTE Links CSS-Klassen zuweisen können

### ISSUE THREAD

**Issue by netzlum** [rpi-virtuell/ci-site#14]
Es wäre gut im RTE den Links gezielt Klassen zuweisen zu können. Im Moment werden nach außen verlinkte Bilder auch mit dem "externer Link"_icon versehen, weil das CSS nach dem enthaltenen URL schaut. Kann man den RTE so midifizieren, dass im Verlinkungs-Popup eine Klassenauswahl zur Verfügung steht?
![Bildschirmfoto am 2019-05-22 um 11 11 59-fullpage](https://user-images.githubusercontent.com/2383882/58162517-9e9a0f00-7c82-11e9-93d9-e23a1c59fed6.png)

**Comment by johappel** [comment]
Den tiny_mce zu manipulieren wäre aufwendig und auch nicht benutzerfreundlich.
Man kann ja bei den Linkoptionen "in neuem Fenster öffnen" anklicken.
Das wird im Attribute target=_blank eingetragen, welches ich widerum für die die css Formatierung nutzen kann

`a[target=' _blank'] {   background: url(...);}`
