### ISSUE TITLE
Sprache in WP und Woocommerce auf formal ändern

### ISSUE THREAD

**Issue by netzlum** [rpi-virtuell/ci-site#4]
Ich vermute, dass der Checkout-Vorgang im Shop mit formalem Deutsch ausgegeben werden soll. Mit installiertem WPMl lässt sich die WP-Sprache aber nicht mehr einfach in den Einstellungen umstellen. Wenn die formale Sprachfassung erst nach der Installation von Woocommerce einegrichtet werden soll, hat woocommerce schon die Strings aus der WP-Standardsprache geladen. 
Wie läasst sich das umstellen?

**Comment by staude** [comment]
habe die Sprache in WP auf de_DE_formal gestellt und das Language Fallback Plugin aktiviert, und de_DE als Fallback ausgewählt. 
Allerdings werden einige Text aus der Übersetzung beim aktivieren von Woo in die DB übertragen und sind über das Backend Pflegbar. Alles das unter Woocommerce/Einstellungen, dort muss das noch händisch umgeschrieben werden
