### ISSUE TITLE
In Toolset-Layouts Sidebar in weiteres div wrappen

### ISSUE THREAD

**Issue by netzlum** [rpi-virtuell/ci-site#9]
Damit in den Toolset-Layouts auf Seiten die Seitenleiste genauso funktionieren kann, wie in den archive-templates müsste die Seitenleiste noch von einem Container (archive-sidebar) umgeben werden. 
In Toolset habe ich dafür keine Möglichkeit gefunden.

**Comment by johappel** [comment]
Wenn du ein weitere Div brauchst, kannst du weitere Grid Cell via Toolset einfügen.

![image](https://user-images.githubusercontent.com/307023/55236191-abc0f180-522f-11e9-9ecf-7bf13e4ef9ed.png)

![image](https://user-images.githubusercontent.com/307023/55236166-9e0b6c00-522f-11e9-846b-12092a090229.png)

![image](https://user-images.githubusercontent.com/307023/55236219-be3b2b00-522f-11e9-9fec-3cf051e97bc0.png)
